export const featuresData = [
  {
    src: "/assets/featuresDetails1.png",
    title: "Digital CRYPTO Wallet",
    tags: "Framer - SaaS",
    bg: "bg-[#10002B]",
    gradient: "bg-[linear-gradient(180deg,_#0D011A_0%,_#1E0039_100%)]",
    slug: "Digital-CRYPTO-Wallet",
    year: "2023",
    description: "An intuitive crypto wallet designed for SaaS platforms.",
    heroImage: "/assets/DCW1.png",
    workFlowImage: "/assets/DCW2.png",
    slides: [
      "/assets/DCWslide1.png",
      "/assets/DCWslide2.png",
      "/assets/DCWslide3.png",
      "/assets/DCWslide4.png",
    ],
  },
  {
    src: "/assets/featuresDetails2.png",
    title: "Zyvo Fintech",
    tags: "WordPress - Fashion",
    gradient:
      "bg-[linear-gradient(122.05deg,_#1E1E1E_6.83%,_#274AFF_49.74%,_#1E1E1E_92.01%)]",
    slug: "Zyvo-Fintech",
    year: "2024",
    description: "A stylish UI for a fashion-focused WordPress app.",
    heroImage: "/assets/Zyvo1.png",
    workFlowImage: "/assets/Zyvo2.png",
    slides: [
      "/assets/Zyvoslide1.png",
      "/assets/Zyvoslide2.png",
      "/assets/Zyvoslide3.png",
      "/assets/Zyvoslide4.png",
    ],
  },
  {
    src: "/assets/featuresDetails3.png",
    title: "Bunon Fashion",
    tags: "UI/UX Design - SaaS",
    gradient: "bg-[linear-gradient(180deg,_#220202_0%,_#212429_100%)]",
    slug: "Bunon-Fashion",
    year: "2022",
    description: "Sleek UX design for a fintech platform.",
    heroImage: "/assets/HMC1.png",
    workFlowImage: "/assets/HMC2.png",
    slides: [
      "/assets/HMCslide1.png",
      "/assets/HMCslide2.png",
      "/assets/HMCslide3.png",
      "/assets/HMCslide4.png",
    ],
  },
  {
    src: "/assets/Featured1.png",
    title: "Half Million Coffee",
    tags: "UI/UX Design - SaaS",
    gradient:
      "bg-[linear-gradient(122.05deg,_#1E1E1E_6.83%,_#4A7639_49.74%,_#1E1E1E_92.01%)]",
    slug: "Half-Million-Coffee",
    year: "2023",
    description: "Smart UI design focused on growth and conversions.",
    heroImage: "/assets/HMC1.png",
    workFlowImage: "/assets/HMC2.png",
    slides: [
      "/assets/HMCslide1.png",
      "/assets/HMCslide2.png",
      "/assets/HMCslide3.png",
      "/assets/HMCslide4.png",
    ],
  },
];
